//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\PropositionalLogicGrammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class PropositionalLogicGrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		CONCLUSION=1, CONJUNCTION=2, DISJUNCTION=3, IMPLICATION=4, LITERAL=5, 
		NEGATION=6, LETTER=7, LBRACKET=8, RBRACKET=9, LCURLYBRACKET=10, RCURLYBRACKET=11, 
		WHITESPACE=12, INVALID=13, COMMA=14;
	public const int
		RULE_statement = 0, RULE_expression = 1;
	public static readonly string[] ruleNames = {
		"statement", "expression"
	};

	private static readonly string[] _LiteralNames = {
		null, "'|='", "'&'", "'v'", "'->'", null, "'~'", null, "'('", "')'", "'{'", 
		"'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "CONCLUSION", "CONJUNCTION", "DISJUNCTION", "IMPLICATION", "LITERAL", 
		"NEGATION", "LETTER", "LBRACKET", "RBRACKET", "LCURLYBRACKET", "RCURLYBRACKET", 
		"WHITESPACE", "INVALID", "COMMA"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PropositionalLogicGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PropositionalLogicGrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PropositionalLogicGrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PropositionalLogicGrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StatementContext : ParserRuleContext {
		public ITerminalNode LCURLYBRACKET() { return GetToken(PropositionalLogicGrammarParser.LCURLYBRACKET, 0); }
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode RCURLYBRACKET() { return GetToken(PropositionalLogicGrammarParser.RCURLYBRACKET, 0); }
		public ITerminalNode CONCLUSION() { return GetToken(PropositionalLogicGrammarParser.CONCLUSION, 0); }
		public ITerminalNode Eof() { return GetToken(PropositionalLogicGrammarParser.Eof, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(PropositionalLogicGrammarParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(PropositionalLogicGrammarParser.COMMA, i);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPropositionalLogicGrammarVisitor<TResult> typedVisitor = visitor as IPropositionalLogicGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 0, RULE_statement);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 4; Match(LCURLYBRACKET);
			State = 8;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 5; expression(0);
					State = 6; Match(COMMA);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 10;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			State = 12; expression(0);
			State = 13; Match(RCURLYBRACKET);
			State = 14; Match(CONCLUSION);
			State = 15; expression(0);
			State = 16; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DisjunctionContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode DISJUNCTION() { return GetToken(PropositionalLogicGrammarParser.DISJUNCTION, 0); }
		public DisjunctionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.EnterDisjunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.ExitDisjunction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPropositionalLogicGrammarVisitor<TResult> typedVisitor = visitor as IPropositionalLogicGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDisjunction(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LiteralContext : ExpressionContext {
		public ITerminalNode LITERAL() { return GetToken(PropositionalLogicGrammarParser.LITERAL, 0); }
		public LiteralContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.EnterLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.ExitLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPropositionalLogicGrammarVisitor<TResult> typedVisitor = visitor as IPropositionalLogicGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ConjunctionContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode CONJUNCTION() { return GetToken(PropositionalLogicGrammarParser.CONJUNCTION, 0); }
		public ConjunctionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.EnterConjunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.ExitConjunction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPropositionalLogicGrammarVisitor<TResult> typedVisitor = visitor as IPropositionalLogicGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConjunction(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ImplicationContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode IMPLICATION() { return GetToken(PropositionalLogicGrammarParser.IMPLICATION, 0); }
		public ImplicationContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.EnterImplication(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.ExitImplication(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPropositionalLogicGrammarVisitor<TResult> typedVisitor = visitor as IPropositionalLogicGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImplication(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenthesesContext : ExpressionContext {
		public ITerminalNode LBRACKET() { return GetToken(PropositionalLogicGrammarParser.LBRACKET, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode RBRACKET() { return GetToken(PropositionalLogicGrammarParser.RBRACKET, 0); }
		public ParenthesesContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.EnterParentheses(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.ExitParentheses(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPropositionalLogicGrammarVisitor<TResult> typedVisitor = visitor as IPropositionalLogicGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParentheses(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class InvalidContext : ExpressionContext {
		public ITerminalNode INVALID() { return GetToken(PropositionalLogicGrammarParser.INVALID, 0); }
		public InvalidContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.EnterInvalid(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPropositionalLogicGrammarListener typedListener = listener as IPropositionalLogicGrammarListener;
			if (typedListener != null) typedListener.ExitInvalid(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPropositionalLogicGrammarVisitor<TResult> typedVisitor = visitor as IPropositionalLogicGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInvalid(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 25;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LBRACKET:
				{
				_localctx = new ParenthesesContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 19; Match(LBRACKET);
				State = 20; expression(0);
				State = 21; Match(RBRACKET);
				}
				break;
			case LITERAL:
				{
				_localctx = new LiteralContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 23; Match(LITERAL);
				}
				break;
			case INVALID:
				{
				_localctx = new InvalidContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 24; Match(INVALID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 38;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 36;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
					case 1:
						{
						_localctx = new ImplicationContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 27;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 28; Match(IMPLICATION);
						State = 29; expression(6);
						}
						break;
					case 2:
						{
						_localctx = new DisjunctionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 30;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 31; Match(DISJUNCTION);
						State = 32; expression(5);
						}
						break;
					case 3:
						{
						_localctx = new ConjunctionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 33;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 34; Match(CONJUNCTION);
						State = 35; expression(4);
						}
						break;
					}
					} 
				}
				State = 40;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		case 1: return Precpred(Context, 4);
		case 2: return Precpred(Context, 3);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x10', ',', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x6', 
		'\x2', '\v', '\n', '\x2', '\r', '\x2', '\xE', '\x2', '\f', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '\x1C', '\n', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\'', '\n', 
		'\x3', '\f', '\x3', '\xE', '\x3', '*', '\v', '\x3', '\x3', '\x3', '\x2', 
		'\x3', '\x4', '\x4', '\x2', '\x4', '\x2', '\x2', '\x2', '/', '\x2', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x4', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x6', '\n', '\a', '\f', '\x2', '\x2', '\a', '\b', '\x5', '\x4', '\x3', 
		'\x2', '\b', '\t', '\a', '\x10', '\x2', '\x2', '\t', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\n', '\a', '\x3', '\x2', '\x2', '\x2', '\v', '\f', '\x3', 
		'\x2', '\x2', '\x2', '\f', '\n', '\x3', '\x2', '\x2', '\x2', '\f', '\r', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\xE', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'\xF', '\x5', '\x4', '\x3', '\x2', '\xF', '\x10', '\a', '\r', '\x2', '\x2', 
		'\x10', '\x11', '\a', '\x3', '\x2', '\x2', '\x11', '\x12', '\x5', '\x4', 
		'\x3', '\x2', '\x12', '\x13', '\a', '\x2', '\x2', '\x3', '\x13', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x14', '\x15', '\b', '\x3', '\x1', '\x2', 
		'\x15', '\x16', '\a', '\n', '\x2', '\x2', '\x16', '\x17', '\x5', '\x4', 
		'\x3', '\x2', '\x17', '\x18', '\a', '\v', '\x2', '\x2', '\x18', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\x1C', '\a', '\a', '\x2', '\x2', 
		'\x1A', '\x1C', '\a', '\xF', '\x2', '\x2', '\x1B', '\x14', '\x3', '\x2', 
		'\x2', '\x2', '\x1B', '\x19', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '(', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x1E', '\f', '\a', '\x2', '\x2', '\x1E', '\x1F', '\a', '\x6', '\x2', 
		'\x2', '\x1F', '\'', '\x5', '\x4', '\x3', '\b', ' ', '!', '\f', '\x6', 
		'\x2', '\x2', '!', '\"', '\a', '\x5', '\x2', '\x2', '\"', '\'', '\x5', 
		'\x4', '\x3', '\a', '#', '$', '\f', '\x5', '\x2', '\x2', '$', '%', '\a', 
		'\x4', '\x2', '\x2', '%', '\'', '\x5', '\x4', '\x3', '\x6', '&', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '&', ' ', '\x3', '\x2', '\x2', '\x2', '&', 
		'#', '\x3', '\x2', '\x2', '\x2', '\'', '*', '\x3', '\x2', '\x2', '\x2', 
		'(', '&', '\x3', '\x2', '\x2', '\x2', '(', ')', '\x3', '\x2', '\x2', '\x2', 
		')', '\x5', '\x3', '\x2', '\x2', '\x2', '*', '(', '\x3', '\x2', '\x2', 
		'\x2', '\x6', '\f', '\x1B', '&', '(',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
