//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\PropositionalLogicGrammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPropositionalLogicGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class PropositionalLogicGrammarBaseListener : IPropositionalLogicGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] PropositionalLogicGrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] PropositionalLogicGrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Disjunction</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisjunction([NotNull] PropositionalLogicGrammarParser.DisjunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Disjunction</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisjunction([NotNull] PropositionalLogicGrammarParser.DisjunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Literal</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] PropositionalLogicGrammarParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Literal</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] PropositionalLogicGrammarParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Conjunction</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConjunction([NotNull] PropositionalLogicGrammarParser.ConjunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Conjunction</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConjunction([NotNull] PropositionalLogicGrammarParser.ConjunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Implication</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplication([NotNull] PropositionalLogicGrammarParser.ImplicationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Implication</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplication([NotNull] PropositionalLogicGrammarParser.ImplicationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Parentheses</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParentheses([NotNull] PropositionalLogicGrammarParser.ParenthesesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Parentheses</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParentheses([NotNull] PropositionalLogicGrammarParser.ParenthesesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Invalid</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInvalid([NotNull] PropositionalLogicGrammarParser.InvalidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Invalid</c>
	/// labeled alternative in <see cref="PropositionalLogicGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInvalid([NotNull] PropositionalLogicGrammarParser.InvalidContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
